Feat/dialog resources
NDLA-H5P/h5p-topic-map pull request #128
Opened 2022-01-05 09:33 UTC by SNujiy

2022-01-07 09:07 UTC, kentis approved these changes
lgtm

2022-01-07 09:07 UTC, kentis commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +  const [cList, setList] = React.useState(customLinks);
are these used?

2022-01-10 05:16 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +  const [cList, setList] = React.useState(customLinks);
Those are not supposed to be part of my last commit, a keyboard slip. Those are used with the newest commits from the weekend. 

Please take another review if you have the chance!

2022-01-10 09:59 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +      </div>
Are the end users supposed to add their own links?

2022-01-10 10:22 UTC, boyum commented
Should we store the custom links in localstorage with the card's/arrow's id?

2022-01-10 10:57 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  top: 433px;
veeeeery specific

2022-01-10 10:59 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +      </div>
Wrap this in a `form` instead of a div and get enter to submit for free. We use `type=button` because `submit` will reload the page.

```suggestion
      <form>
        <input
          className={styles.input}
          type="text"
          placeholder="www.nyresurss.no"
          onChange={e => updateLink(e.target.value)}
          ref={input => {
            inputField = input;
          }}
        />
        <button
          className={styles.inputButton}
          type="button"
          onClick={() => updateCustomList()}
        >
          Legg til
        </button>
      </form>
```

2022-01-10 13:07 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +      </div>
Good catch!

2022-01-10 13:27 UTC, SNujiy commented
> Should we store the custom links in localstorage with the card's/arrow's id?

I don't think we have localstorage setup atm, maybe we should handle this in a new issue?

2022-01-10 14:46 UTC, boyum commented
> > Should we store the custom links in localstorage with the card's/arrow's id?
> 
> I don't think we have localstorage setup atm, maybe we should handle this in a new issue?

Sure

2022-01-10 20:56 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +      </div>
Yes, a new issue for local storage will be issued soon.

2022-01-11 13:07 UTC, SNujiy commented
/rebase

2022-01-11 13:18 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +          onChange={e => updateLink(e.target.value)}
This could possibly be made even simpler?

```suggestion
          onChange={e => setLink(e.target.value)}
```

2022-01-11 14:06 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +      <p> Relevante lenker: </p>
Variables are added, translation will be added from another pull request.

2022-01-11 14:07 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +  const inputFieldRef = React.useRef<HTMLInputElement>();
```suggestion
  const inputFieldRef = React.useRef<HTMLInputElement>(null);
```

2022-01-11 14:08 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.tsx
> +  const inputFieldRef = React.useRef<HTMLInputElement>();
Already fixed :)

2022-01-11 14:27 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  top: 433px;
These absolute values won't do anything as the element has `position: static`.

```suggestion
```

2022-01-11 14:27 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  top: 433px;
These absolute values won't do anything as the element has `position: static`.

```suggestion
```

2022-01-11 14:29 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 85px;
Use padding instead of absolute width. `Legg til` is wider than `Add`, while the translation in some languages might be much longer and won't fit within 85px.

```suggestion
  padding: 0 1rem;
```

2022-01-11 14:30 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  height: 32px;
Use rems instead of px values for text height values. Some users might have set all font sizes to 400%, which would not fit within 32px of height.

```suggestion
  height: 2rem;
```

2022-01-11 14:31 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  height: 32px;
Use rems instead of px values for text height values. Some users might have set all font sizes to 400%, which would not fit within 32px of height.

```suggestion
  height: 2rem;
  width: 14rem;
```

2022-01-11 14:35 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 85px;
With this in mind, we should really set this on the wrapper div:

```scss
display: flex;

input[type=text] {
  flex-grow: 1;
}
```

2022-01-11 14:53 UTC, SNujiy commented
/rebase

2022-01-12 08:38 UTC, boyum requested changes

2022-01-12 08:40 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 14rem;
Hard coded widths should be avoided, but this will _probably_ be ok also on small phones.
```suggestion
  // TODO: Add `display: flex` to container and switch out the hard coded `width` for `flex-grow: 1`
  width: 14rem;
```

2022-01-12 19:52 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 14rem;
Is this todo for another pr or?

2022-01-12 20:01 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 14rem;
You decide. It's such a small change that I'd make it part of this one.

2022-01-12 20:53 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  width: 14rem;
Fixed width by `flex-grow: 0`?

2022-01-12 20:59 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  flex-grow: 0;
Flex-grow: 1 will make the element take up the remaining space

```suggestion
  flex-grow: 1;
```

2022-01-12 21:04 UTC, boyum approved these changes

2022-01-13 07:07 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  flex-grow: 0;
With `display: flex  `the input element will take up the entire width of the screen on PC as well. That looks a bit strange?

2022-01-13 07:30 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  flex-grow: 0;
Yeah, we should add a `max-width: 19.5rem` to the container as well

2022-01-13 07:31 UTC, boyum commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  flex-grow: 0;
Or just keep it as is

2022-01-13 07:35 UTC, SNujiy commented on src/components/Dialog-Window/Resources/DialogResources.module.scss
> +  flex-grow: 0;
We can add a max-width to the container

2022-01-13 07:50 UTC, boyum approved these changes
Nice!

2022-01-13 07:52 UTC, SNujiy commented
/rebase

2022-01-13 08:09 UTC, merged